apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wire-pod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/gaubien2000/learn_argocd.git'
    targetRevision: main
    path: apps/wire-pod
    directory:
      exclude: '{Dockerfile.hardened,apiConfig.escape-pod.json,persistent-entrypoint.sh,wirepod-advertise-ip.patch}'
  destination:
    server: https://kubernetes.default.svc
    namespace: wire-pod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
