apiVersion: v1
kind: Namespace
metadata:
  name: media
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
      - name: qbittorrent
        image: ghcr.io/linuxserver/qbittorrent:latest
        ports:
        - containerPort: 8080   # WebUI
        - containerPort: 6881   # TCP peer
        - containerPort: 6881   # UDP peer
          protocol: UDP
        env:
        - name: PUID
          value: "1000"   # check with `id -u pi`
        - name: PGID
          value: "1000"   # check with `id -g pi`
        - name: TZ
          value: "Etc/UTC"
        - name: WEBUI_PORT
          value: "8080"
        - name: QB_WEBUI_HOST_HEADER_VALIDATION
          value: "false"
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
      volumes:
      - name: config
        hostPath:
          path: /home/pi/qbittorrent/config
          type: DirectoryOrCreate
      - name: downloads
        hostPath:
          path: /home/pi/qbittorrent/downloads
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: media
spec:
  type: NodePort
  selector:
    app: qbittorrent
  ports:
  - name: webui
    port: 8080
    targetPort: 8080
    nodePort: 32080
  - name: torrent-tcp
    port: 6881
    targetPort: 6881
    nodePort: 32681
  - name: torrent-udp
    port: 6881
    targetPort: 6881
    nodePort: 32682
    protocol: UDP

